export const carAttributes = {
  transmission: [
    { value: "manual", label: "Manuell" },
    { value: "automatic", label: "Automat" },
  ],
  drive: [
    { value: "rear_wheel", label: "Bakhjulsdrift" },
    { value: "front_wheel", label: "Framhjulsdrift" },
    { value: "four_wheel", label: "Fyrhjulsdrift" },
  ],

  marken: [
    { value: "volvo", label: "Volvo" },
    { value: "saab", label: "Saab" },
    { value: "ford", label: "Ford" },
    { value: "bmw", label: "BMW" },
    { value: "mercedes", label: "Mercedes-Benz" },
    { value: "audi", label: "Audi" },
    { value: "volkswagen", label: "Volkswagen" },
    { value: "toyota", label: "Toyota" },
    { value: "honda", label: "Honda" },
    { value: "nissan", label: "Nissan" },
  ],
  modellAr: [
    { value: "2000", label: "2000" },
    { value: "2001", label: "2001" },
    { value: "2002", label: "2002" },
    { value: "2003", label: "2003" },
    { value: "2004", label: "2004" },
    { value: "2005", label: "2005" },
    { value: "2006", label: "2006" },
    { value: "2007", label: "2007" },
    { value: "2008", label: "2008" },
    { value: "2009", label: "2009" },
    { value: "2010", label: "2010" },
    { value: "2011", label: "2011" },
    { value: "2012", label: "2012" },
    { value: "2013", label: "2013" },
    { value: "2014", label: "2014" },
    { value: "2015", label: "2015" },
    { value: "2016", label: "2016" },
    { value: "2017", label: "2017" },
    { value: "2018", label: "2018" },
    { value: "2019", label: "2019" },
    { value: "2020", label: "2020" },
    { value: "2021", label: "2021" },
    { value: "2022", label: "2022" },
    { value: "2023", label: "2023" },
    { value: "2024", label: "2024" },
    { value: "2025", label: "2025" },
  ],

  pris: [
    { value: "5000", label: "5 000 kr" },
    { value: "10000", label: "10 000 kr" },
    { value: "15000", label: "15 000 kr" },
    { value: "20000", label: "20 000 kr" },
    { value: "25000", label: "25 000 kr" },
    { value: "30000", label: "30 000 kr" },
    { value: "35000", label: "35 000 kr" },
    { value: "40000", label: "40 000 kr" },
    { value: "45000", label: "45 000 kr" },
    { value: "50000", label: "50 000 kr" },
  ],
  miltal: [
    { value: "0", label: "0 mil" },
    { value: "5000", label: "5 000 mil" },
    { value: "10000", label: "10 000 mil" },
    { value: "15000", label: "15 000 mil" },
    { value: "20000", label: "20 000 mil" },
    { value: "25000", label: "25 000 mil" },
    { value: "30000", label: "30 000 mil" },
  ],
  drivmedel: [
    { value: "petrol", label: "Bensin" },
    { value: "biogas", label: "Biogas" },
    { value: "ethanol", label: "Etanol" },
    { value: "el", label: "El" },
  ],
  bodyType: [
    { value: "station_wagon", label: "Kombi" },
    { value: "family_car", label: "Familjebil" },
    { value: "sedan", label: "Sedan" },
    { value: "suv", label: "SUV" },
  ],
  seats: [{ value: "seven_seater", label: "7-sits" }],
  colors: [
    { value: "black", label: "Svart" },
    { value: "white", label: "Vit" },
    { value: "gold", label: "Guld" },
    { value: "yellow", label: "Gul" },
    { value: "orange", label: "Orange" },
    { value: "pink", label: "Rosa" },
    { value: "red", label: "Röd" },
    { value: "brown", label: "Brun" },
    { value: "green", label: "Grön" },
    { value: "blue", label: "Blå" },
    { value: "purple", label: "Lila" },
    { value: "grey", label: "Grå" },
    { value: "multicoloured", label: "Mångfärgad" },
    { value: "light_brown", label: "Ljusbrun" },
    { value: "light_green", label: "Ljusgrön" },
    { value: "light_blue", label: "Ljusblå" },
    { value: "dark_brown", label: "Mörkbrun" },
    { value: "dark_green", label: "Mörkgrön" },
    { value: "dark_blue", label: "Mörkblå" },
    { value: "bright_red", label: "Klarröd" },
    { value: "bright_green", label: "Klargrön" },
    { value: "bright_blue", label: "Klarblå" },
  ],
  condition: [
    { value: "new", label: "Ny" },
    { value: "used", label: "Begagnad" },
  ],
  receipt: [
    { value: "yes", label: "Ja" },
    { value: "no", label: "Nej" },
  ],
};
